[env:esp32-dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    mrfaptastic/ESP32 HUB75 LED MATRIX PANEL DMA Display@^3.0.0
    bblanchon/ArduinoJson@^7.2.0
    adafruit/Adafruit GFX Library@^1.11.0
