[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    ESP32-HUB75-MatrixPanel-I2S-DMA
    bblanchon/ArduinoJson@^7.0.0
build_src_filter = +<*> -<.git/> -<.svn/>
build_flags =
    -DCORE_DEBUG_LEVEL=0
